# Generated by Django 5.2 on 2025-04-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_used',
        ),
    ]
